apiVersion: v1
kind: Service
metadata:
  name: football-network-db
spec:
  ports:
  - port: 3306
  selector:
    app: csro_mysql
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: csro_mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csro_mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: brujula61
        - name: MYSQL_DATABASE
          value: footballnetwork
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: csro_mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: csro_mysql-persistent-storage
        persistentVolumeClaim:
          claimName: csro_mysql-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csro_mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: csro_mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"